name: SignManager
main: com.rezzedup.signmanager.SignManager
version: 2.0
author: RezzedUp
commands:
  sign:
    aliases: [signmanager, sm, signedit, se, editsign, managesign]
    description: Modify a sign.
permissions:
  signmanager.*:
    description: Allows access to all com.rezzedup.signmanager.SignManager features.
    default: op
    children:
      signmanager.colors: true
      signmanager.command: true
  signmanager.colors:
    description: Gives players the ability to create colorful signs.
    default: op
  signmanager.command:
    description: Allows usage to the /sign command.
    default: op
